### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by skerkour** [skerkour/bloom#17]
## Tasks
* [x] update user avatar api
* [x] update user avatar service
* [x] update group avatar api
* [x] update group avatar avatar service
* [x] serve avatar service
* [x] serve avatar api
* [x] api response with avatars
* [x] webapp: user avatar service
* [x] webapp: user avatar ui
* [x] webapp: group avatar service
* [x] webapp: group avatar ui
* [x] avatar_url using base_url

**Comment by skerkour** [comment]
closed by a0c361bf104e83ddc00f9092847b302f0efb7aea
