### ISSUE TITLE
Remove stripe requirement for self hosting

### ISSUE THREAD

**Issue by clonex10100** [skerkour/bloom#49]
I wanted to try self hosting a personal bloom instance, but it looks like I need to connect it to stripe for it to work. It wasn't happy with my commenting out/removing the stripe information in the .env file. Is there any way around this?

**Comment by skerkour** [comment]
Hi,
Thank you for the report. Indeed it's a bug and not a feature.
I will try to produce a roadmap to fix this issue this afternoon :)

**Comment by skerkour** [comment]
# Tasks
* [ ] config: make stripe optional
* [ ] config: check that stripe is not empty is self_hosting == true
* [ ] before using stripe data, check if self_hosting == true

**Comment by skerkour** [comment]
Hey @clonex10100 the issue is fixed. The new Docker image should be available in ~30 mins so you'll have to `docker pull ghcr.io/skerkour/bloom:latest`

Please open a new issue if you encounter other difficulties self-hosting Bloom.
Have a great day
