### ISSUE TITLE
newsletter: remove message.name field

### ISSUE THREAD

**Issue by skerkour** [skerkour/bloom#61]
## Tasks
* [ ] bloom: remove from db
* [ ] bloom: remove from entities
* [ ] bloom: remove from API models
* [ ] webapp: remove from API models
