### ISSUE TITLE
webapp: leftbar

### ISSUE THREAD

**Issue by skerkour** [skerkour/bloom#64]
## Tasks
* [x] leftbar on desktop
* [x] preferences and billings
* [x] fix scrolling
* [x] fix drawer
* [ ] workspace switch on `/app` page (for mobiles) + preferences + billing

**Comment by skerkour** [comment]
https://github.com/skerkour/bloom-legacy/blob/main/desktop/src/ui/kernel/components/LeftBar.vue

**Comment by skerkour** [comment]
https://github.com/skerkour/bloom-legacy/blob/main/website/public/static/imgs/landing/hero.png
